version: 2.1

jobs:
  build-backend:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    working_directory: ~/project/backend
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Restore dependencies
          command: dotnet restore SecurePaymentsPortal.csproj

      - run:
          name: Build backend
          command: dotnet build SecurePaymentsPortal.csproj --configuration Release --no-restore

      - run:
          name: Run unit tests
          command: dotnet test SecurePaymentsPortal.csproj --no-build || true


  dependency-scan:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    working_directory: ~/project/backend
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Software Composition Analysis (SCA)
          command: |
            echo "Checking vulnerable packages..."
            dotnet list SecurePaymentsPortal.csproj package --vulnerable > vulnerabilities-report.txt || true

      - run:
          name: Show SCA results
          command: cat vulnerabilities-report.txt

      - store_artifacts:
          path: vulnerabilities-report.txt


  sonar-scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: SonarQube Static Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=SecurePaymentsPortal \
              -Dsonar.sources=backend \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.login=$SONAR_TOKEN


  build-frontend:
    docker:
      - image: node:18
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build React app
          command: npm run build


workflows:
  security-pipeline:
    jobs:
      - build-backend
      - dependency-scan:
          requires:
            - build-backend
      - sonar-scan:
          requires:
            - build-backend
      - build-frontend:
          requires:
            - build-backend